### PR TITLE
Implement turn & freeze instructions

### PR DESCRIPTION
**Pull request by fredy20501**
## Work Completed
- Implemented RotationDetector.
  - Note: it also includes tilt instructions, but I didn't add them into the game yet since they only make sense if the device is in "portrait" orientation. If we want them, I made a separate ticket to add logic to know, depending on the current device orientation, which way is "left" and "forward".
- Created RotateTestActivity to test the RotationDetector.
- Implemented turn left/right and don't turn instructions using the RotationDetector.
- Implemented freeze instruction:
  - Modified RotationDetector & ShakeDetector to also have a "move" output. This is a special instruction that triggers a game over when the current instruction is freeze.
- Added game mode ideas in `GameMode.java`

### CODE REVIEW

**Comment by carterjmoore** [comment]
After defeating the demon in my phone, I was able to test the turning, and can confirm that it works. I saw you also have detection set up for forward and backwards tilting. Do you think we should add those as actions too?

**Comment by fredy20501** [comment]
> After defeating the demon in my phone, I was able to test the turning, and can confirm that it works. I saw you also have detection set up for forward and backwards tilting. Do you think we should add those as actions too?

See the note in the PR description:
- Note: it also includes tilt instructions, but I didn't add them into the game yet since they only make sense if the device is in "portrait" orientation. If we want them, I made a separate ticket to add logic to know, depending on the current device orientation, which way is "left" and "forward".

**Comment by carterjmoore** [comment]
> > After defeating the demon in my phone, I was able to test the turning, and can confirm that it works. I saw you also have detection set up for forward and backwards tilting. Do you think we should add those as actions too?
> 
> See the note in the PR description:
> 
> * Note: it also includes tilt instructions, but I didn't add them into the game yet since they only make sense if the device is in "portrait" orientation. If we want them, I made a separate ticket to add logic to know, depending on the current device orientation, which way is "left" and "forward".

Oh, I was wondering what that comment meant, I see now. Would they still work if you just have the auto-rotate on your phone turned off though?

**Comment by fredy20501** [comment]
> Oh, I was wondering what that comment meant, I see now. Would they still work if you just have the auto-rotate on your phone turned off though?

The issue is that the axis of rotation is relative to the orientation of the device. Ex: the y-axis would point "up" (from the user's perspective) if you hold your device in front of you in portrait mode. But if the device is on its side, the y-axis could point "left" or "right" (from the user's perspective).



Now this is not a problem if we force users to hold their device in portrait mode, but some devices (like tablets) have a preferred orientation of landscape and forcing those devices into portrait mode might lead to a worse user experience.

**Review by carterjmoore — APPROVED** [review]
this sucks :( 😠 👎 🤒 🤕

**Review by hsavoie — APPROVED** [review]
B2 🥈

**Pull request merged**
